### ISSUE TITLE
cmake config files not included in package

### ISSUE THREAD

**Issue by maxnoe** [conda-forge/cfitsio-feedstock#42]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For using cfitsio via cmake, it would be great if the `cfitsio-config.cmake` and related cmake files that come with recent versions of cfitsio would also be included in this package.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by pkgw** [comment]
An implementation note: it looks like to do this correctly we'd need to switch the build system over to CMake, since the Autoconf system doesn't have code to generate the CMake files from the templates. It would *probably* be fine to fill in those templates ourselves, but I would worry about variable definitions differing subtly between CMake and Autotools.

And if we switch the build system, we should be careful that the resulting shared libraries are binary compatible, the same headers get installed, etc. Once again, everything will *probably* be OK but it's important to check carefully.
